common:
  app:
    name: Loopin
    dir: '{appName}/'
    ofxLoopinData: bin/data/ofxLoopin

  openframeworks:
    dir: openFrameworks
    version: 0.9.3
    release_url: http://openframeworks.cc/versions/v{openframeworks.version}/

  addons:
    ofxKinect: true
    ofxLoopin:
      git: https://github.com/koopero/ofxLoopin.git
    ofxJSON:
      git: https://github.com/jefftimesten/ofxJSON.git
    ofxSyphon:
      git: https://github.com/astellato/ofxSyphon.git


linux:
  openframeworks:
    zip_name: of_v{openframeworks.version}_{platform}_release.tar.gz
    projectGenerator: apps/projectGenerator/commandLine/bin/projectGenerator
    projectGeneratorPath: apps/projectGenerator/commandLine
  app:
    executable: bin/{appName}

darwin:
  openframeworks:
    zip_name: of_v{openframeworks.version}_{platform}_release.zip
    projectGenerator: projectGenerator-osx/projectGenerator.app/Contents/Resources/app/app/projectGenerator
  app:
    executable: bin/{appName}.app/Contents/MacOS/{appName}
