#!/bin/sh
':' //; exec "$(command -v nodejs || command -v node)" "$0" "$@"

const native = require('../src/builder')
    , yaml = require('js-yaml')
    , argparse = require('argparse')
    , pkg = require('../package.json')
    , parser = new argparse.ArgumentParser({
        version: pkg.version,
        addHelp: true,
      })

addArgparseArguments( parser )


const opt = parser.parseArgs()

native( opt )
.then( function ( build ) {
  console.log( build.process )
  if ( build.process ) {
    build.process.stdout.pipe( process.stdout )
    build.process.stderr.pipe( process.stderr )
    process.stdin.pipe( build.process.stdin )
  }
} )


function addArgparseArguments( parser ) {
  parser.addArgument(
    ['-r', '--run'],
    {
      help: 'Run the Loopin exec',
      action: 'storeTrue'
    }
  )

  parser.addArgument(
    ['--verbose'],
    {
      help: 'Log everything',
      action: 'storeTrue'
    }
  )

  parser.addArgument(
    ['-q', '--quiet'],
    {
      help: 'Do not log anything',
      action: 'storeTrue'
    }
  )

}
